### ISSUE TITLE
Question: Contributing to the project

### ISSUE THREAD

**Issue by FredHappyface** [osmanonurkoc/papirusadaptive#1]
Hello,

This is a great project and I would very much like to contribute to it. Was wondering if you had any beginners guidance? I've taken a look through the project and can't find how you are pulling the icons into the app and forming symlinks.

Thank you for your time and for bringing Papirus to Android

**Comment by osmanonurkoc** [comment]
Hello,

I'm sory for late. I don't have lot free time because my university has started.
If you want to help project you can draw icons for missing ones. I can forward icon requests to you. 

The first thing you need to do. Draw background and foreground picture, which is 432x432px.
For example: [foreground](https://github.com/osmanonurkoc/papirusadaptive/blob/master/app/src/main/res/mipmap-xxxhdpi/ms_word2_foreground.png) and [background](https://github.com/osmanonurkoc/papirusadaptive/blob/master/app/src/main/res/mipmap-xxxhdpi/ms_word2_background.png)

After you must learn the main activity of application you are drawing the icon to. 
[Use this](https://drive.google.com/file/d/1P7z-Ats6g0Ao1aPJWLtFg1zcPVErMobz/view?usp=sharing) (Standart icon request tool)

And the last one. Attach icon pictures to request mail.

I almost forgot. if we come to the symlinks. Use this scheme↓
`    <item component="ComponentInfo{}" drawable="" />
`

 ComponentInfo{**main activity of app**} 
 drawable="**icon name on papirus eg. ms_word2 for Microsoft Word**" />


Sorry for spelling and other things. Thank you.

**Comment by FredHappyface** [comment]
Hi,

Thanks for getting back to me. Looks great. I'll take a look at this
